default:
    path:  /
    defaults: { _controller: AthenaChatBundle:Chat:welcome }
    
users:
    path:  /users
    defaults: { _controller: AthenaChatBundle:Chat:users }

Conversation:
    type:     rest
    resource: Athena\ChatBundle\Controller\ConversationController