default:
    path:  /
    defaults: { _controller: AthenaChatBundle:Chat:welcome }

users:
    path:  /users
    defaults: { _controller: AthenaChatBundle:Chat:users }


sandbox:
    path: /sandbox
    defaults: {_controller: AthenaChatBundle:Sandbox:welcome }