imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      nodeUrl: "http://athena.example.com:3000"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AthenaChatBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUserBundle
fos_user:
    db_driver:     orm                        # Type de bdd -> Doctrine
    firewall_name: main                       # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Athena\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    registration:
        form:
            type: athena_user_registration
            validation_groups: [AthenaRegistration]
    from_email:
        address:        noreply@athena.com
        sender_name:    Athena Chat

#HWIOAuthBundle
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebookId
            google: googleId
    resource_owners:
        google:
            type:                google
            client_id:           1092872845945-iprvu46hvm3rubr7557hhjfgebm5eads.apps.googleusercontent.com
            client_secret:       wfmMW2t-mEui4hHFLcXfaMPh
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
        # facebook:
        #     type:                facebook
        #     client_id:           "facebook_app_id"
        #     client_secret:       "facebook_app_secret"
        #     scope:               ""

sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
        
services:
  controller.pre_execute_listener:
    class: Athena\ChatBundle\Listener\ControllerListener
    tags:
      -  { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

jms_serializer:
  metadata:
    debug: true
    file_cache:
      dir: "%kernel.cache_dir%/serializer"
    auto_detection: true
    directories:
      FOSUserBundle:
        namespace_prefix: FOS\UserBundle
        path: "@AthenaAjaxBundle/Resources/config/serializer"

#deploy:
#  prod:
#    rsync-options: '-azC --force --delete --progress -h --checksum'
#    host: 37.187.117.209
#    dir: /home/www/athena
#    user: www
#    port: 22
#    timeout: 120 # Connection timeout in seconds. 0 for no timeout.
#    post_deploy_operations:
#        - app/console cache:clear --env=prod
#        - app/console assets:install --env=prod
#        - app/console assetic:dump --env=prod
