security:
    encoders:
        Athena\UserBundle\Entity\User: sha512
    providers:
        main:
            id: fos_user.user_provider.username_email
        # my_custom_hwi_provider:
        #     id: ib_user.oauth_user_provider
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            oauth:
                resource_owners:
                    facebook:       "/login/check-facebook"
                    google:         "/login/check-google"
                login_path:         /login
                failure_path:       /login

                oauth_user_provider:
                    #this is the custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:
                path:   fos_user_security_logout
                target: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-google, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/google$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
