<?php

namespace Athena\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository
{

    /**
     * Récupère la conversation dont l'identifiant est en paramètre
     * @param integer $id
     */
    public function findConversation($id)
    {
        if(0 === (int) $id){
            throw new \InvalidArgumentException("La conversation n'existe pas.");
        }

        return $this->find($id);

    }

    public function findConversationByTwoUsers($idConnectedUser, $idOtherUser)
    {

        $q = $this->createQueryBuilder('c');

        $q->leftJoin('c.user_conversation', 'uc1')
            ->leftJoin('c.user_conversation', 'uc2')
            ->leftJoin('c.messages', 'm')
            ->where('uc1.user = :id1')
            ->setParameter('id1', $idConnectedUser)
            ->andWhere('uc2.user = :id2')
            ->setParameter('id2', $idOtherUser)
            ;

        $result = $q->getQuery()->getResult();

        if(count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }


    }




}