<?php

namespace Athena\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository
{

    /**
     * Récupère la conversation dont l'identifiant est en paramètre
     * @param integer $id
     */
    public function findConversation($id)
    {
        if(0 === (int) $id){
            throw new \InvalidArgumentException("La conversation n'existe pas.");
        }

        return $this->find($id);

    }




}