<?php

namespace Athena\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    /**
     * Récupère tous les messages de la conversation $idConversation
     * @param integer $idConversation
     */
    public function fetchAllMessages($idConversation)
    {
        if(0 === (int) $idConversation){
            throw new \InvalidArgumentException("La conversation n'existe pas.");
        }

        return $this->findAll(array("id_conversation" => $idConversation));
    }

}
