<?php

namespace Athena\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * Récupère tous les utilisateurs
     */
    public function fetchAllUsers($idConnected)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.id != :id')
            ->setParameter('id', $idConnected)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Recherche des utilisateurs à partir du nom, du prénom ou du mail
     * @param unknown $keyword
     */
    public function findUsers($keyword, $user = null)
    {

        $q = $this
                ->createQueryBuilder('u')
                ->where('u.username like :keyword')
                ->orWhere('u.firstName like :keyword')
                ->orWhere('u.lastName like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%')
            ;

        if ($user && $user instanceof User) {
            $q->andWhere('u.id != :id')
                ->setParameter('id', $user->getId());
        }

        return $q->getQuery()->getResult();
    }


    /**
     * Récupère toutes les conversations d'un utilisateur
     * @param integer $userId
     */
    public function fetchAllConversations($userId)
    {
        if(0 === (int) $userId){
            throw new \InvalidArgumentException("L'utilisateur n'existe pas.");
        }

        return $this->find(array('id' => $userId))
                    ->getConversations();
    }
	
	
	
	
	
}
